apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vector-db
  template:
    metadata:
      labels:
        app: vector-db
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:latest
        ports:
        - containerPort: 6333
---
apiVersion: v1
kind: Service
metadata:
  name: vector-db
spec:
  type: ClusterIP
  selector:
    app: vector-db
  ports:
    - port: 6333
      targetPort: 6333